SRCS = $(wildcard *.cpp)
OBJS = $(SRCS:.cpp=.o)
PPCXX_DLL = ppcxx.dll

CXX_DEBUG_FLAGS = -g
CXX_PIC_FLAGS = -fPIC
CXXFLAGS = $(CXX_DEBUG_FLAGS) $(CXX_PIC_FLAGS) -w -I../../cxx1/src -DCXX_GENERATOR

all:$(PPCXX_DLL)


$(PPCXX_DLL) : $(OBJS)
	$(CXX) $(CXX_DEBUG_FLAGS) -shared -o $@ $(OBJS)

clean:
	$(RM) *.o *~ *.dll *.so
